Feature/collection
mash-up-kr/yourName-server pull request #92
Opened 2022-02-13 03:23 UTC by AlwaysLee-12

- 도감 추가 DTO의 description IsNotEmpty -> IsOptional
- 중복된 도감 이름으로 추가하는 경우에 대한 예외 추가

2022-02-13 15:23 UTC, god9599 requested changes

2022-02-13 15:23 UTC, god9599 commented on src/modules/collection/collection.service.ts
> +        );
BadRequestException을 위에서 던지는데 여기에 400 처리 코드가 또 들어가네요. 위에 BadRequestException에서 메시지 넣고 처리하는 게 나을 것 같아용

2022-02-13 15:23 UTC, god9599 commented on src/modules/collection/collection.service.ts
> +      }
여기 부분 코드가 바뀌었는데 이러면 단순히 저 메시지만 떠서 원래 코드로 복구하는게 나을 것 같아요. 다른 코드들이랑 통일성도 맞추고요

2022-02-14 01:28 UTC, AlwaysLee-12 commented on src/modules/collection/collection.service.ts
> +        );
try 코드에서 throw를 하면 catch로 또 잡아서 statusCode 500안에 400이 들어가더라구여
그래서 catch문에서 따로 분기처리를 했습니다.
그러면 혹시 이런식의 코드는 어떨까여?
try문 안에 있는 입력으로 들어온 도감의 이름이 존재하는지 체크하는 부분을 없애고, 테이블 상에서 name을 unique로 설정해두고
아래와 같이 처리를 하는 방식입니다.
...
catch(err){
      if (err.errno === 1062) {
        throw new HttpException(
          { statusCode: 400, message: err },
          HttpStatus.BAD_REQUEST,
        );
      }
      throw new HttpException(
        { statusCode: 500, message: err },
        HttpStatus.INTERNAL_SERVER_ERROR,
      );
}

2022-02-14 01:30 UTC, AlwaysLee-12 commented on src/modules/collection/collection.service.ts
> +      }
메세지 부분은 err로 하는게 낫다는 걸까요?
throw new HttpException({statusCode: 500, message: err}, ...)
이런식으로요
안에 response 형식 같은 경우에는 기존의 형식을 예외 응답에도 최대한 유지하는게 낫지 않을까합니다.
(기존 응답 형식: statusCode: , data: , message: , 예외 응답 형식: statusCode: , message: )

2022-02-14 08:49 UTC, god9599 commented on src/modules/collection/collection.service.ts
> +        );
기존 코드보다 괜찮을 것 같네요. 

그 err.errno === 1062 코드로 잡아오는 지 테스트 해보셨나요? 저는 저렇게 써본적은 없어서 궁금하네용

2022-02-14 08:53 UTC, god9599 commented on src/modules/collection/collection.service.ts
> +      }
500떨어지면 서버 에러인거는 아니까 msg는 err 메시지를 떨어뜨려줘야 할 것 같다는 말씀이였어요

그리고, 기존 형식을 예외 응답에도 유지 시키려면 catch 모든 코드를 바꿔줘야 하니까 저는 기존 코드가 나을 것 같다고 말씀드린겁니당

2022-02-15 10:46 UTC, god9599 approved these changes

2022-02-15 10:46 UTC, merged